Repository G-33-movile-applications/flutter, pull requests merged in 2025-10, with the labels that each got.

#9 Login register delivery
  mymeds/assets/Logo.png
  mymeds/assets/delivery_image.avif
  mymeds/lib/main.dart
  mymeds/lib/routes/app_router.dart
  mymeds/lib/services/firebase_service.dart
  mymeds/lib/ui/auth/login_screen.dart
  mymeds/lib/ui/auth/register_screen.dart
  mymeds/lib/ui/delivery/delivery_screen.dart
  mymeds/macos/Flutter/GeneratedPluginRegistrant.swift
  mymeds/pubspec.lock
  mymeds/pubspec.yaml
  mymeds/windows/flutter/generated_plugin_registrant.cc
  mymeds/windows/flutter/generated_plugins.cmake
Labels: good first issue, Sprint 2

#12 Implement UML-Compliant Repository & Façade Updates with Fixed Relationships
  mymeds/REPOSITORY_FACADE_IMPLEMENTATION.md
  mymeds/lib/examples/repository_facade_example.dart
  mymeds/lib/facade/app_repository_facade.dart
  mymeds/lib/main.dart
  mymeds/lib/models/medicamento.dart
  mymeds/lib/models/pedido.dart
  mymeds/lib/models/prescripcion.dart
  mymeds/lib/models/punto_fisico.dart
  mymeds/lib/repositories/medicamento_repository.dart
  mymeds/lib/repositories/pedido_repository.dart
  mymeds/lib/repositories/prescripcion_repository.dart
  mymeds/lib/repositories/punto_fisico_repository.dart
  mymeds/lib/repositories/usuario_repository.dart
  mymeds/lib/services/auth_service.dart
  mymeds/lib/services/user_session.dart
  mymeds/lib/ui/home/home_screen.dart
  mymeds/lib/ui/screens/orders_list_screen.dart
Labels: Sprint 2, Model

#25 ProfileTermiando
  mymeds/lib/routes/app_router.dart
  mymeds/lib/ui/home/home_screen.dart
  mymeds/lib/ui/profile/profile_screen.dart
  mymeds/lib/ui/profile/profile_screen_stub.dart
Labels: Sprint 2
